apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.route.name }}
  labels:
    app: mq-web
spec:
  tls:
  insecureEdgeTerminationPolicy: Redirect
  termination: passthrough
  to:
    kind: Service
    name: mq-web
  wildcardPolicy: {{ .Value.route.wildcardPolicy }}
