apiVersion: v1
kind: Service
metadata:
  name: mq-web
spec:
  selector:
    app: mq
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port:  {{ .Values.service.port }}
    targetPort:  {{ .Values.service.targetPort }}